2024-11-08T13:14:58 {"cpu": 0.06787109375, "cpu_total": 16, "cpu_usage": 0.004241943359375, "memory": 3143.0, "memory_total": 9688.0, "memory_usage": 0.32442196531791906, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071698.440505, "uuid": "08e5b40bdc0246fc99e9a2d92651da0f"}
2024-11-08T13:14:58 {"block_run_id": 18, "block_uuid": "load_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 18: pipeline retail_pipeline block load_order_data", "timestamp": 1731071698.641655, "uuid": "75e3ad05a3ad43109333a6644afc1dd4"}
2024-11-08T13:14:58 {"cpu": 0.06787109375, "cpu_total": 16, "cpu_usage": 0.004241943359375, "memory": 3182.0, "memory_total": 9688.0, "memory_usage": 0.32844756399669695, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071698.642296, "uuid": "0dadd20e205b4cbebacb238995f53f0d"}
2024-11-08T13:14:59 {"block_run_id": 20, "block_uuid": "load_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 20: pipeline retail_pipeline block load_marketing_data", "timestamp": 1731071699.68699, "uuid": "7ee911d8e7ef4b30b2f99569b4ac49be"}
2024-11-08T13:14:59 {"block_run_id": 18, "block_uuid": "load_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 18 (block_uuid: load_order_data) completes.", "timestamp": 1731071699.759755, "uuid": "e0543bf70ec74d358a19e810407f0b0d"}
2024-11-08T13:15:00 {"block_run_id": 20, "block_uuid": "load_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 20 (block_uuid: load_marketing_data) completes.", "timestamp": 1731071700.95058, "uuid": "fa8f9e42e6eb4ddb99d4fa3a667f94ca"}
2024-11-08T13:15:08 {"cpu": 0.09375, "cpu_total": 16, "cpu_usage": 0.005859375, "memory": 3130.0, "memory_total": 9688.0, "memory_usage": 0.3230800990916598, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071708.803518, "uuid": "99a83507f8d04a2f86d1746a0c23a74b"}
2024-11-08T13:15:09 {"block_run_id": 19, "block_uuid": "export_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 19: pipeline retail_pipeline block export_order_data", "timestamp": 1731071709.008315, "uuid": "9ba14752e249470e958646ea37b10213"}
2024-11-08T13:15:10 {"block_run_id": 21, "block_uuid": "export_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 21: pipeline retail_pipeline block export_marketing_data", "timestamp": 1731071710.04323, "uuid": "ca837eade56049abbcef7df582e81ba8"}
2024-11-08T13:15:10 {"block_run_id": 22, "block_uuid": "transform_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 22: pipeline retail_pipeline block transform_order_data", "timestamp": 1731071710.063918, "uuid": "48b4fbce5a504877a64006d7c05e1fc8"}
2024-11-08T13:15:10 {"block_run_id": 23, "block_uuid": "transform_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 23: pipeline retail_pipeline block transform_marketing_data", "timestamp": 1731071710.0639, "uuid": "fe94007afd8d4a0e818ed1cab60186e3"}
2024-11-08T13:15:10 {"block_run_id": 19, "block_uuid": "export_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 19 (block_uuid: export_order_data) completes.", "timestamp": 1731071710.23533, "uuid": "9a345ebec21d4ea48024907479db80b0"}
2024-11-08T13:15:10 {"block_run_id": 23, "block_uuid": "transform_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 23 (block_uuid: transform_marketing_data) completes.", "timestamp": 1731071710.698835, "uuid": "8bb93c7de94a4108b831711fa0bea61c"}
2024-11-08T13:15:10 {"block_run_id": 22, "block_uuid": "transform_order_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 22 (block_uuid: transform_order_data) completes.", "timestamp": 1731071710.73313, "uuid": "f0b136a6302446b5bcbb2daed32b9711"}
2024-11-08T13:15:11 {"block_run_id": 21, "block_uuid": "export_marketing_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 21 (block_uuid: export_marketing_data) completes.", "timestamp": 1731071711.528297, "uuid": "cab414e99a084c409ab851789fb8333c"}
2024-11-08T13:15:18 {"cpu": 0.091796875, "cpu_total": 16, "cpu_usage": 0.0057373046875, "memory": 3138.0, "memory_total": 9688.0, "memory_usage": 0.32390586292320395, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071718.167383, "uuid": "807134ace2ec44f5a2b1459d446bb7c5"}
2024-11-08T13:15:18 {"block_run_id": 24, "block_uuid": "merge_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 24: pipeline retail_pipeline block merge_data", "timestamp": 1731071718.359659, "uuid": "1c677a20b98840b5984e9b77db633a8d"}
2024-11-08T13:15:19 {"block_run_id": 24, "block_uuid": "merge_data", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 24 (block_uuid: merge_data) completes.", "timestamp": 1731071719.654295, "uuid": "9758cd66a0774e4bbc5803ec27cd47f3"}
2024-11-08T13:15:28 {"cpu": 0.09033203125, "cpu_total": 16, "cpu_usage": 0.005645751953125, "memory": 3135.0, "memory_total": 9688.0, "memory_usage": 0.3235962014863749, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071728.392069, "uuid": "c44bfa5c935f41f29d114ff8d2468557"}
2024-11-08T13:15:28 {"block_run_id": 25, "block_uuid": "export_biqquery", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 25: pipeline retail_pipeline block export_biqquery", "timestamp": 1731071728.595544, "uuid": "72321e8308564a7ca7db2783c7f1fec2"}
2024-11-08T13:15:29 {"block_run_id": 26, "block_uuid": "export_merged_data_bucket", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 26: pipeline retail_pipeline block export_merged_data_bucket", "timestamp": 1731071729.636883, "uuid": "4a461bf0c8164b8a9d623967b83c0fd7"}
2024-11-08T13:15:31 {"block_run_id": 25, "block_uuid": "export_biqquery", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "EXCEPTION", "message": "BlockRun 25 (block_uuid: export_biqquery) failed.", "timestamp": 1731071731.18461, "uuid": "34d4bf1e68ac4372856308954a9052f6", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 354, in export\n    __process(database=database, write_disposition=write_disposition)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 252, in __process\n    \"\"\").to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Dataset hardytec-demo-projects:retail_test was not found in location US\n\nLocation: US\nJob ID: 6921224c-6ad6-4916-9231-f7b41295cc98\n\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 800, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1731, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1236, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "404 Not found: Dataset hardytec-demo-projects:retail_test was not found in location US\n\nLocation: US\nJob ID: 6921224c-6ad6-4916-9231-f7b41295cc98\n"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 354, in export
    __process(database=database, write_disposition=write_disposition)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 252, in __process
    """).to_dataframe()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1890, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 104, in wait_for_query
    return query_job.result(max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset hardytec-demo-projects:retail_test was not found in location US

Location: US
Job ID: 6921224c-6ad6-4916-9231-f7b41295cc98

2024-11-08T13:15:31 {"block_run_id": 26, "block_uuid": "export_merged_data_bucket", "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "BlockRun 26 (block_uuid: export_merged_data_bucket) completes.", "timestamp": 1731071731.424161, "uuid": "7a3167f0b53740b08b59956fbbe90800"}
2024-11-08T13:15:38 {"cpu": 0.13232421875, "cpu_total": 16, "cpu_usage": 0.008270263671875, "memory": 3149.0, "memory_total": 9688.0, "memory_usage": 0.3250412881915772, "pipeline_run_id": 3, "pipeline_schedule_id": 3, "pipeline_uuid": "retail_pipeline", "hostname": "df1d6c2b2160", "level": "INFO", "message": "Pipeline retail_pipeline for run 3 in schedule 3 is alive.", "timestamp": 1731071738.670015, "uuid": "343c229585404e448afd9abc39561c47"}
